name: github pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Encode Access Token
        id: token
        uses: LarchLiu/encode-secret-action@v0.1.1
        with:
          access_token: ${{ secrets.ACTIONS_TRIGGER_TOKEN }}    

      - uses: bahmutov/npm-install@v1

      - run: |
          npm run build
        env:
          NODE_ENV: production
          VUE_APP_GITHUB_TOKEN: ${{ steps.token.outputs.access_token }}
 
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist